services:
  backend:
    image: ghcr.io/smart-web-elements/customer-medusa:latest
    restart: unless-stopped
    container_name: customer-backend
    depends_on:
      - postgres
      - redis
    entrypoint: [ "./starter.sh", "start --port 7000" ]
    volumes:
      - ./uploads:/app/medusa/.medusa/server/static
    env_file: .env
    expose:
      - 7000
    networks:
      - default
      - customer-default

  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: customer-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./ssl/server.key:/var/lib/postgresql/server.key:ro
      - ./ssl/server.crt:/var/lib/postgresql/server.crt:ro
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "5432:5432"
    networks:
      - customer-default

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: customer-redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - customer-default

networks:
  default:
    name: nginx-proxy
    external: true
  customer-default:
