services:
  webhook:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - /root/.docker:/root/.docker
      - /var/www/docker_sites/webhook/data:/etc/webhook/data:ro
      - /var/www/docker_sites/websites:/etc/webhook/websites
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/image:/var/lib/docker/image
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
    expose:
      - 9000
    networks:
      - default
    command:
      - '-hooks=/etc/webhook/data/hooks.json'
      - '-hotreload'

networks:
  default:
    name: nginx-proxy
    external: true
