services:
  app:
    image: swe.registry.jetbrains.space/p/PROJECT/PACKAGE/IMAGE:TAG
    restart: always
    environment:
      VIRTUAL_HOST: website.s-w-e.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: website.s-w-e.com
      LETSENCRYPT_EMAIL: info@s-w-e.com
    expose:
      - 3000
    networks:
      - default

networks:
  default:
    name: nginx-proxy
    external: true